language: java
jdk: openjdk8

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
  - tar xzvf apache-maven-3.5.4-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.5.4/bin:$PATH
  - mvn -v
