version: "3.7"

services:
  niord-proxy:
    image: "${DOCKER_REGISTRY:-dmadk}/${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: "niord-proxy"
    ports:
      - 9090:8080
    volumes:
      - ${NIORD_HOME}:/opt/niord
    environment:
      - EXECUTION_MODE=${PROXY_EXECUTION_MODE}
      - NIORD_PROXY_SERVER=${NIORD_APPSRV_SERVER}
      - NIORD_REPO_PATH=/opt/niord/repo
      - NIORD_PROXY_AREAS=${PROXY_AREAS}
      - NIORD_REPO_TYPE=${PROXY_REPO_TYPE}
      - NIORD_PROXY_WMS_URL=${PROXY_WMS_URL}
    logging:
      driver: "json-file"
      options:
          max-size: "1g"
          max-file: "3"
    restart: unless-stopped
    network_mode: bridge